"""
Pangenome base class for gig-map-io.
"""

from functools import cached_property, lru_cache
import hashlib
from pathlib import Path
import sys
from typing import Any, Dict, List
from Bio import Phylo
import pandas as pd
import numpy as np
from plotly import graph_objects as go
import plotly.express as px
import matplotlib.pyplot as plt
from Bio.Phylo.TreeConstruction import DistanceMatrix, DistanceTreeConstructor
from Bio.Phylo.BaseTree import Tree, Clade
from plotly.subplots import make_subplots

from ..helpers.sort_dataframe import sort_dataframe
from ..helpers.save_image import save_image
from ..helpers.coords import Coords
from .dataset import Dataset
from ..helpers.phylogeny import Phylogeny

from logging import getLogger
import logging

logger = getLogger(__name__)
logger.setLevel(logging.INFO)
logger.addHandler(logging.StreamHandler(stream=sys.stdout))

class Pangenome(Dataset):
    """
    Representation of a pangenome generated by gig-map.

    This is a minimal base class; concrete subclasses or helpers can add
    convenience methods for common gig-map outputs (e.g., gene presence/absence,
    annotations, etc.).

    DataFrame attributes are cached after first access to avoid reloading
    CSV files on subsequent accesses.
    """

    def __repr__(self) -> str:
        return f"Pangenome(directory={self.directory})"

    def __str__(self) -> str:
        return f"Pangenome(directory={self.directory})"

    def __format__(self, format_spec: str) -> str:
        return f"Pangenome(directory={self.directory})"

    @cached_property
    def unbinned_genes_all_genomes_html(self) -> str:
        """
        Gene by genome heatmap HTML loaded from bin_pangenome/heatmap.unbinned_genes_all_genomes.html.
        """
        path = self.directory / "bin_pangenome/heatmap.unbinned_genes_all_genomes.html"
        return path.read_text()

    @cached_property
    def gene_bins(self) -> pd.DataFrame:
        """
        Gene bins DataFrame loaded from bin_pangenome/gene_bins.csv.

        Returns
        -------
        DataFrame containing gene bin assignments.
        """
        path = self.directory / "bin_pangenome" / "gene_bins.csv"
        return (
            pd.read_csv(path)
            .assign(
                gene_label=lambda d: d.apply(
                    lambda r: f"{r['gene_id']} - {r['combined_name']}",
                    axis=1
                )
            )
        )

    def bin_contains_term(self, bin: str, term: str) -> bool:
        """
        Check if a bin contains a term, even as a substring.
        """
        return self.gene_bins.query(f"bin == '{bin}'")["combined_name"].str.contains(term).any()

    @cached_property
    def ani_distances(self) -> pd.DataFrame:
        """
        ANI distances DataFrame loaded from distances.csv.gz.

        Returns
        -------
        DataFrame containing ANI distances.
        """
        path = self.directory / "distances.csv.gz"
        return pd.read_csv(path, index_col=0)

    @cached_property
    def align_genomes(self) -> pd.DataFrame:
        """
        Alignment of genomes from align/genomes.aln.csv.gz.
        """
        path = self.directory / "align" / "genomes.aln.csv.gz"
        df = pd.read_csv(path)

        # Add the bin label to the alignment
        df = df.assign(
            bin=df["sseqid"].apply(
                self.gene_bins.set_index("gene_id")["bin"].get
            )
        )
        return df

    @cached_property
    def n_bins(self) -> int:
        """
        Number of unique (non-null) bins in gene_bins.
        """
        return int(self.gene_bins["bin"].dropna().nunique())

    @cached_property
    def bin_names(self) -> list[str]:
        """
        List of unique (non-null) bin names in gene_bins.
        """
        return self.gene_bins["bin"].dropna().unique().tolist()

    @cached_property
    def n_genes(self) -> int:
        """
        Number of genes which are part of bins in the pangenome.
        """
        return int(self.gene_bins.dropna(subset=["bin"]).shape[0])

    @cached_property
    def n_genomes(self) -> int:
        """
        Number of genomes in the pangenome.
        """
        return int(self.align_genomes["genome"].dropna().nunique())

    @cached_property
    def align_genomes_long(self) -> pd.DataFrame:
        """
        Content of align/genomes.aln.csv.gz (long format).
        """
        path = self.directory / "align" / "genomes.aln.csv.gz"
        return pd.read_csv(path, low_memory=False, index_col=0)

    @cached_property
    def genome_content(self) -> pd.DataFrame:
        """
        Genome content DataFrame loaded from bin_pangenome/genome_content.long.csv.

        Returns
        -------
        DataFrame containing genome content data.
        """
        path = self.directory / "bin_pangenome" / "genome_content.long.csv"
        return pd.read_csv(path, low_memory=False)

    @cached_property
    def bin_presence_wide(self) -> pd.DataFrame:
        """
        Wide dataframe of bin presence/absence for each genome. Each column is a bin, each row is a genome.
        """
        return (
            self.genome_content
            .assign(present=(self.genome_content["prop_genes_detected"] >= 0.5).astype(int))
            .reindex(columns=["genome", "bin", "present"])
            .dropna()
            .drop_duplicates()
            .pivot(
                index="genome",
                columns="bin",
                values="present"
            )
            .fillna(0)
        )

    @cached_property
    def bin_size(self) -> pd.DataFrame:
        """
        Number of genes in each bin.
        """
        return self.gene_bins["bin"].value_counts()

    def bin_genome_heatmap(
        self,
        width: int = 500,
        height: int = 400,
        file_prefix: str | None = None
    ) -> go.Figure:
        """
        Heatmap of bin presence/absence for each genome.
        """

        # Perform hierarchical clustering on the rows and columns
        wide_sorted = sort_dataframe(
            sort_dataframe(
                self.bin_presence_wide.copy().T,
                method="ward"
            ).T,
            method="ward"
        )

        # Set the edges of the bins so that the widths match the number of genes
        x = [0] + self.bin_size.reindex(wide_sorted.columns.values).cumsum().tolist()

        fig = go.Figure(
            data=[
                go.Heatmap(
                    z=wide_sorted.values,
                    x=x,
                    colorscale="blues",
                    showscale=False
                )
            ],
            layout=go.Layout(
                xaxis_title="Gene",
                yaxis_title="Genome",
                template="simple_white",
                width=width,
                height=height
            )
        )
        # If save_image was provided, use the string as the file
        # prefix to write out HTML, PDF, PNG, and JSON
        save_image(fig, file_prefix)

        return fig

    def calc_membership_vs_distance(
        self,
        min_n_genomes: int = 10,
        max_n_genomes: int = 100,
        n_genes: int = 100,
        max_distance: int = 1000000
    ) -> pd.DataFrame:
        """
        For a random subset of genes, compute how similar they are in terms
        of their membership across all genomes, and then also compute their
        typical physical distance across those genomes (when they are both present).
        Then plot the relationship between these two metrics.

        To prevent a skewing by bin size, we'll randomly select a subset of bins
        and then randomly select a subset of genes from each bin.

        Parameters
        ----------
        min_n_genomes: int
            Minimum number of genomes that a gene must be present in to be considered.
        max_n_genomes: int
            Maximum number of genomes that a gene can be present in to be considered.
        n_genes: int
            Number of genes to select from each bin (up to the size of the bin).
        max_distance: int
            Maximum distance to consider for the genomic coordinates (in bp).

        Returns
        -------
        DataFrame containing the membership and distance metrics.
        """

        n_genomes_per_gene = (
            self.align_genomes_long
            .reindex(columns=["sseqid", "genome"])
            .drop_duplicates()
            ["sseqid"]
            .value_counts()
        )
        genes_passing_filter = n_genomes_per_gene.loc[lambda x: (x >= min_n_genomes) & (x <= max_n_genomes)].index.tolist()

        # Pick a random subset of the genes
        genes = np.random.choice(genes_passing_filter, size=n_genes, replace=False)

        # Subset the align_genomes_long DataFrame to just the selected genes
        df = (
            self.align_genomes_long
            .loc[self.align_genomes_long["sseqid"].isin(genes)]
            .assign(
                gene_position=lambda d: d["qstart"] + d["qend"] / 2
            )
        )

        # Compare each pair of genes to compute the membership and distance
        output = []
        for gene1, df1 in df.groupby("sseqid"):
            for gene2, df2 in df.groupby("sseqid"):
                if gene1 <= gene2:
                    continue
                output.append(dict(
                    gene1=gene1,
                    gene2=gene2,
                    membership=len(set(df1["genome"]) & set(df2["genome"])) / len(set(df1["genome"]) | set(df2["genome"])),
                    distance=self._compute_gene_distance(df1, df2, max_distance)
                ))

        return pd.DataFrame(output)

    def _compute_gene_distance(self, df1: pd.DataFrame, df2: pd.DataFrame, max_distance: int) -> float:
        """
        Compute the distance between two genes.
        """
        df = pd.concat([
            df1.assign(gene=lambda d: "gene1"),
            df2.assign(gene=lambda d: "gene2")
        ]).pivot(
            index=["genome", "qseqid"],
            columns="gene",
            values="gene_position"
        ).dropna()

        if df.shape[0] == 0:
            return max_distance
        else:
            return min(max_distance, np.abs(df["gene1"] - df["gene2"]).mean())

    def compare_membership_vs_distance(
        self,
        n_genes: int = 100,
        min_n_genomes: int = 10,
        max_n_genomes: int = 100,
        width: int = 500,
        height: int = 400,
        file_prefix: str | None = None,
        **kwargs: dict[str, Any]
    ) -> go.Figure:
        """
        For a random subset of genes, compute how similar they are in terms
        of their membership across all genomes, and then also compute their
        typical physical distance across those genomes (when they are both present).
        Then plot the relationship between these two metrics.
        """

        df = (
            self.calc_membership_vs_distance(min_n_genomes, max_n_genomes, n_genes)
            .assign(
                distance_log10=lambda d: np.log10(d["distance"]),
                membership_bins=lambda d: d["membership"].apply(lambda x: round(x, 1))
            )
        )

        fig = px.box(
            data_frame=df,
            x="membership_bins",
            y="distance_log10",
            template="plotly_white",
            labels=dict(
                distance_log10="Mean Distance (bp)",
                membership_bins="Genome Membership<br>(Jaccard Similarity)"
            ),
            width=width,
            height=height,
            **kwargs
        )
        fig.update_yaxes(
            tickmode='array',
            tickvals=[0, 1, 2, 3, 4, 5, 6],
            ticktext=["1", "10", "100", "1k", "10k", "100k", "1M"]
        )

        save_image(fig, file_prefix)
        return fig

    def bin_size_df(
        self,
        bins: int = 30,
    ) -> pd.DataFrame:
        """
        Histogram of bin sizes.
        """
        # Get the bin sizes
        vals = self.bin_size.copy().apply(np.log10)

        counts, bins = np.histogram(
            vals,
            bins=bins,
            weights=self.bin_size.copy()
        )

        bin_names = [
            (
                f"{10**bins[i-1]:.0f} - {10**bins[i]:.0f}"
            )
            for i in range(1, len(bins))
        ]
        bins = 0.5 * (bins[:-1] + bins[1:])

        return pd.DataFrame(dict(
            bin_size=bins,
            count=counts,
            bin_names=bin_names
        ))

    def bin_size_histogram(
        self,
        bins: int = 30,
        width: int = 500,
        height: int = 400,
        file_prefix: str | None = None
    ) -> go.Figure:

        df = self.bin_size_df(bins)

        fig = px.bar(
            data_frame=df,
            x="bin_size",
            y="count",
            labels=dict(
                bin_size="Pangenome Bin Size (# of Genes)",
                count="Total Gene Content"
            ),
            template="plotly_white",
            hover_name="bin_names",
            width=width,
            height=height
        )
        fig.update_xaxes(
            tickmode='array',
            tickvals=[0, 1, 2, 3, 4, 5],
            ticktext=["1", "10", "100", "1k", "10k", "100k"]
        )
        # If save_image was provided, use the string as the file
        # prefix to write out HTML, PDF, PNG, and JSON
        save_image(fig, file_prefix)

        return fig

    def rarefaction_curve_data(_self, n_reps: int = 10) -> pd.DataFrame:
        data = []
        for rep in range(n_reps):
            # Take the bin presence matrix
            bin_presence = _self.bin_presence_wide.copy()
            # Shuffle the rows
            bin_presence = bin_presence.sample(frac=1).reset_index(drop=True)
            # Compute the cumulative sum by column (bin)
            cs = bin_presence.cumsum()
            # For each row, count the number of genes recovered
            n_genes = (cs > 0) * _self.bin_size
            data.append(pd.DataFrame(dict(
                n_genomes=list(range(1, bin_presence.shape[0] + 1)),
                n_genes=n_genes.sum(axis=1)
            )))
        return (
            pd.concat(data)
            .groupby("n_genomes")
            ["n_genes"]
            .describe()
            .reset_index()
        )

    def rarefaction_curve(
        self,
        n_reps: int = 10,
        width: int = 500,
        height: int = 400,
        file_prefix: str | None = None
    ) -> go.Figure:
        """
        Rarefaction curve of the pangenome.

        Parameters
        ----------
        n_reps: int
            Number of rarefaction replicates to simulate.

        Returns
        -------
        Plotly figure of the rarefaction curve.
        """
        # Simulate the number of genes recovered with different numbers of subsampled genomes
        rf = self.rarefaction_curve_data(n_reps)

        fig = go.Figure(
            data=[
                go.Scatter(
                    x=rf["n_genomes"],
                    y=rf["50%"],
                    mode="lines",
                    line=dict(color='rgb(31, 119, 180)'),
                    showlegend=False
                ),
                go.Scatter(
                    x=rf['n_genomes'],
                    y=rf['75%'],
                    mode='lines',
                    marker=dict(color="#444"),
                    line=dict(width=0),
                    showlegend=False
                ),
                go.Scatter(
                    x=rf['n_genomes'],
                    y=rf['25%'],
                    marker=dict(color="#444"),
                    line=dict(width=0),
                    mode='lines',
                    fillcolor='rgba(68, 68, 68, 0.3)',
                    fill='tonexty',
                    showlegend=False
                )
            ],
            layout=go.Layout(
                xaxis_title="Number of Genomes",
                yaxis_title="Number of Genes",
                yaxis_range=[0, None],
                template="plotly_white",
                width=width,
                height=height
            )
        )

        # Make the x axis log scale
        fig.update_xaxes(
            type="log"
        )

        # If save_image was provided, use the string as the file
        # prefix to write out HTML, PDF, PNG, and JSON
        save_image(fig, file_prefix)

        return fig

    def bin_gene_map(
        self,
        bin: str,
        width: int = 5,
        height: int = 5,
        remove_gene_id = True,
        remove_org_tag = True,
        text_offset = 0.025,
        file_prefix: str | None = None
    ) -> go.Figure:
        """
        Map of genes in a bin.
        """

        # Get a DataFrame with the gene coordinates
        # inferred from all of the genome alignments
        coords, group_offset = self._get_gene_coords(bin)

        # Customize the names
        coords = coords.assign(
            gene_label=coords['gene'].apply(self.gene_bins.set_index("gene_id")["gene_label"].get),
            label=lambda d: d['gene_label'].apply(
                lambda gene: self.customize_label(gene, remove_gene_id, remove_org_tag)
            )
        )

        max_x = np.max([coords['start'].max(), coords['stop'].max()])
        min_x = np.min([coords['start'].min(), coords['stop'].min()])
        span_x = max_x - min_x

        coords = coords.assign(
            start_x=lambda d: (d['start'] - min_x) / span_x,
            stop_x=lambda d: (d['stop'] - min_x) / span_x
        )

        fig, ax = plt.subplots(figsize=(width, height))
        for ix, r in coords.iterrows():

            ax.annotate(
                "",
                xytext=(r['start_x'], 0),
                xy=(r['stop_x'], 0),
                arrowprops=dict(arrowstyle="simple")
            )
            ax.plot([r['start_x'], r['stop_x']], [0, 0], linewidth=0)

            ax.annotate(
                '',
                xytext=((ix + 0.5) / coords.shape[0], text_offset),
                xy=(np.mean([r['start_x'], r['stop_x']]), text_offset / 5.),
                arrowprops=dict(arrowstyle="-"),
                horizontalalignment='left',  # Align text to the right of its position
                verticalalignment='center'
            )
            ax.text(
                (ix + 0.5) / coords.shape[0],
                text_offset,
                r['label'],
                rotation=90,
                horizontalalignment='center',
                verticalalignment='bottom'
            )

        # The vertial lines work with an increment scaled to the text offset
        vertical_increment = text_offset / 10.

        # Draw a line to indicate each of the group offsets
        # It should be styled as a small vertical red line
        for offset_x in (group_offset / span_x).values:
            if offset_x > 0:
                ax.annotate(
                    '',
                    xytext=(offset_x, 0),
                    xy=(offset_x, -4 * vertical_increment),
                    arrowprops=dict(arrowstyle="-", color="red")
                )

        # Draw a line underneath the entire gene map
        ax.annotate(
            '',
            xytext=(0, -2 * vertical_increment),
            xy=(1, -2 * vertical_increment),
            arrowprops=dict(arrowstyle="|-|")
        )

        # Write the size underneath
        if span_x > 1000000:
            size_label = f"{span_x / 1000000:.1f} Mb"
        elif span_x > 1000:
            size_label = f"{span_x / 1000:.1f} Kb"
        else:
            size_label = f"{span_x:.0f} bp"
        ax.text(
            0.5,
            - (text_offset),
            size_label,
            horizontalalignment='center',
            verticalalignment='bottom'
        )

        ax.axis("off")

        # If save_image was provided, use the string as the file
        # prefix to write out HTML, PDF, PNG, and JSON
        save_image(fig, file_prefix)

        # Optionally save the relative gene coordinates as CSV
        if file_prefix is not None:
            coords.to_csv(file_prefix + ".csv", index=False)

        return fig

    def _get_gene_coords(self, bin: str) -> pd.DataFrame:
        """
        Get the coordinates for every gene across every genome
        Filter to just the genes in this bin
        """
        aln = self.align_genomes.query(f"bin == '{bin}'")
        output = []
        while len(aln) > 0:
            output.append(Coords(aln).to_df())
            if len(output[-1]) == 0:
                break
            aln = aln.loc[~aln['sseqid'].isin(output[-1]['gene'])]

        df = pd.concat([df.assign(group=i) for i, df in enumerate(output)])

        # Assign a set of global coordinates to each gene
        # This will take into account the size of each group, which is the
        # maximum start or stop value within each group.
        group_sizes = (
            df.assign(end=df[['start', 'stop']].max(axis=1))
            .groupby("group")
            ['end'].max()
        )
        # To use those to build the global coordinates, take the cumulative sum
        group_offset = group_sizes.cumsum() - group_sizes
        
        df = df.assign(
            start=df["start"] + df["group"].apply(group_offset.get),
            stop=df["stop"] + df["group"].apply(group_offset.get)
        ).reset_index(drop=True)

        return df, group_offset

    @staticmethod
    def customize_label(label: str, remove_gene_id: bool, remove_org_tag: bool):
        if remove_gene_id:
            if label.startswith("Bin "):
                label = " - ".join(label.split(" - ", 2)[[0, 2]])
            else:
                label = label.split(" - ", 1)[1]
        if remove_org_tag:
            if " [" in label:
                label = label.rsplit(" [", 1)[0]
            if "MULTISPECIES: " in label:
                label = label.replace("MULTISPECIES: ", "")

        return label

    def bin_presence_heatmap(
        self,
        bins: str | List[str],
        width: int = 500,
        height: int = 400,
        title: str = "Bin Presence Heatmap",
        show_ani_tree: bool = True,
        show_genome_names: bool = False,
        tree_proportion: float = 0.5,
        horizontal_spacing: float = 0.,
        file_prefix: str | None = None
    ) -> go.Figure:
        """
        Heatmap of bin presence/absence for each genome.
        Parameters
        ----------
        bins: str | List[str]
            The bins to plot.
        width: int
            The width of the figure.
        height: int
            The height of the figure.
        file_prefix: str | None
            The prefix for the file to save the figure to.

        Returns
        -------
        Plotly figure of the heatmap.
        """

        if isinstance(bins, str):
            bins = [bins]

        # Get the genomes that this bin is found in
        df = (
            self.genome_content
            .loc[self.genome_content["bin"].isin(bins)]
            .assign(present=1)
            .pivot_table(index="genome", columns="bin",values="present")
            .reindex(index=self.genome_content["genome"].unique(), columns=bins)
            .fillna(0)
            .astype(int)
        )
        df = df[df.index.notnull()]

        left_tree = self.ani_tree
        df = df.reindex(index=left_tree.leaves_list)

        fig = make_subplots(
            rows=1,
            cols=1 + int(show_ani_tree),
            shared_yaxes=True,
            horizontal_spacing=horizontal_spacing,
            column_widths=[tree_proportion, 1.-tree_proportion] if show_ani_tree else [1.]
        )
        if show_ani_tree:
            left_tree.plot_lines(fig, row=1, col=1)
            left_tree.plot_points(fig, mode="markers", row=1, col=1)

        fig.add_heatmap(
            z=df.values,
            x=df.columns.values,
            y=list(range(df.shape[0])),
            colorscale="blues",
            showscale=False,
            row=1,
            col=1 + int(show_ani_tree)
        )

        fig.update_layout(
            height=height,
            width=width,
            template="simple_white",
            title=dict(text=title, x=0.5, xanchor="center")
        )
        if show_genome_names:
            fig.update_yaxes(
                tickmode="array",
                tickvals=list(range(df.shape[0])),
                ticktext=df.index.values,
                side='right',
                anchor="x2"
            )
        else:
            fig.update_yaxes(
                visible=False
            )
        
        # If save_image was provided, use the string as the file
        # prefix to write out HTML, PDF, PNG, and JSON
        save_image(fig, file_prefix)
        return fig

    @cached_property
    def ani_tree(self) -> Phylogeny:
        # Get the ANI distances
        ani_dist = self.ani_distances.copy()

        # Make a distance matrix in BioPython format
        dm = DistanceMatrix(
            names=list(ani_dist.index.values),
            matrix=[
                l[:(i+1)]
                for i, l in enumerate(ani_dist.values.tolist())
            ]
        )

        # Compute a hash of the ani_dist DataFrame which can be used to identify the tree
        tree_hash = hashlib.sha256(ani_dist.to_csv().encode()).hexdigest()

        # Cache the NJ tree as Newick, using the hash as the filename
        cache_file = Path(f".cache/pangenome_ani_tree/{tree_hash}.nwk")
        if cache_file.exists():
            logger.info(f"Loading ANI tree from cache: {cache_file}")
            tree = Phylo.read(cache_file, "newick")
        else:
            logger.info(f"Computing ANI tree and caching to: {cache_file}")
            constructor = DistanceTreeConstructor()
            tree = constructor.nj(dm)
            tree.root_at_midpoint()
            cache_file.parent.mkdir(exist_ok=True, parents=True)
            Phylo.write(tree, cache_file, "newick")

        distances = pd.DataFrame(dm.matrix, index=dm.names, columns=dm.names)

        return Phylogeny(
            name="ANI",
            tree=tree,
            distances=distances
        )