"""
Pangenome base class for gig-map-io.
"""

from functools import cached_property
import hashlib
import logging
from pathlib import Path
from typing import Any, Dict, List
from Bio import Phylo
import pandas as pd
import numpy as np
from plotly import graph_objects as go
import plotly.express as px
import matplotlib.pyplot as plt
from Bio.Phylo.TreeConstruction import DistanceMatrix, DistanceTreeConstructor
from plotly.subplots import make_subplots

from ..helpers.clustering import linkage_order
from ..helpers.save_image import save_image
from ..helpers.style import PRIMARY, SIMPLE_TEMPLATE, TEMPLATE
from ..helpers.coords import Coords
from ..helpers.gene_context import draw_gene_labels, order_rows, plot_gene_context
from ..helpers.genomes import genbank_duplicates
from .dataset import Dataset
from ..helpers.phylogeny import Phylogeny

logger = logging.getLogger(__name__)

def _largest_cluster(genes: pd.DataFrame, max_gap: int) -> pd.DataFrame:
    """The longest run of genes, by count, in which no two neighbors are more than ``max_gap`` apart."""
    ordered = genes.sort_values("start")
    starts = ordered["start"].values
    breaks = np.flatnonzero(np.diff(starts) > max_gap) + 1
    runs = np.split(np.arange(len(ordered)), breaks)
    best = max(runs, key=lambda run: (len(run), -run[0]))
    return ordered.iloc[best]


def _short_genome_name(genome: str) -> str:
    """An assembly file name reduced to its accession and strain, e.g. GCF_000210575.1 ASM21057v1."""
    name = genome.replace("_genomic.fna.gz", "").replace(".fna.gz", "").replace(".fasta", "")
    parts = name.split("_", 2)
    if len(parts) == 3 and parts[0] in ("GCA", "GCF"):
        return f"{parts[0]}_{parts[1]} {parts[2]}"[:34]
    return name[:34]


class Pangenome(Dataset):
    """
    Representation of a pangenome generated by gig-map.

    This is a minimal base class; concrete subclasses or helpers can add
    convenience methods for common gig-map outputs (e.g., gene presence/absence,
    annotations, etc.).

    DataFrame attributes are cached after first access to avoid reloading
    CSV files on subsequent accesses.
    """

    def __repr__(self) -> str:
        return f"Pangenome(directory={self.directory})"

    @cached_property
    def gene_bins(self) -> pd.DataFrame:
        """
        Gene bins DataFrame loaded from bin_pangenome/gene_bins.csv.

        Returns
        -------
        DataFrame containing gene bin assignments.
        """
        path = self.directory / "bin_pangenome" / "gene_bins.csv"
        return (
            pd.read_csv(path)
            .assign(
                gene_label=lambda d: d.apply(
                    lambda r: f"{r['gene_id']} - {r['combined_name']}",
                    axis=1
                )
            )
        )

    @cached_property
    def ani_distances(self) -> pd.DataFrame:
        """
        ANI distances DataFrame loaded from distances.csv.gz.

        Returns
        -------
        DataFrame containing ANI distances.
        """
        path = self.directory / "distances.csv.gz"
        return pd.read_csv(path, index_col=0)

    @cached_property
    def align_genomes(self) -> pd.DataFrame:
        """
        Alignment of genomes from align/genomes.aln.csv.gz.
        """
        path = self.directory / "align" / "genomes.aln.csv.gz"
        df = pd.read_csv(path)

        # Add the bin label to the alignment
        df = df.assign(
            bin=df["sseqid"].apply(
                self.gene_bins.set_index("gene_id")["bin"].get
            )
        )
        return df

    @cached_property
    def bin_names(self) -> list[str]:
        """
        List of unique (non-null) bin names in gene_bins.
        """
        return self.gene_bins["bin"].dropna().unique().tolist()

    @cached_property
    def genome_content(self) -> pd.DataFrame:
        """
        Genome content DataFrame loaded from bin_pangenome/genome_content.long.csv.

        Returns
        -------
        DataFrame containing genome content data.
        """
        path = self.directory / "bin_pangenome" / "genome_content.long.csv"
        return pd.read_csv(path, low_memory=False)

    @cached_property
    def bin_presence_wide(self) -> pd.DataFrame:
        """
        Wide dataframe of bin presence/absence for each genome. Each column is a bin, each row is a genome.
        """
        return (
            self.genome_content
            .assign(present=(self.genome_content["prop_genes_detected"] >= 0.5).astype(int))
            .reindex(columns=["genome", "bin", "present"])
            .dropna()
            .drop_duplicates()
            .pivot(
                index="genome",
                columns="bin",
                values="present"
            )
            .fillna(0)
        )

    @cached_property
    def bin_size(self) -> pd.DataFrame:
        """
        Number of genes in each bin.
        """
        return self.gene_bins["bin"].value_counts()

    def core_genome(self, prop_genes_detected: float = 0.9) -> str:
        """
        The bin that best represents the core genome of this pangenome.

        Picks the bin detected near-completely (at least `prop_genes_detected`
        of its genes) in the largest number of genomes, breaking ties by the
        number of genes in the bin.
        """
        counts = (
            self.genome_content
            .query(f"prop_genes_detected >= {prop_genes_detected}")
            .groupby("bin")
            .size()
            .to_frame(name="n_genomes")
            .assign(n_genes=self.bin_size)
            .sort_values(by=["n_genomes", "n_genes"], ascending=False)
        )
        return counts.index.values[0]

    def bin_genome_heatmap(
        self,
        width: int = 500,
        height: int = 400,
        file_prefix: str | None = None
    ) -> go.Figure:
        """
        Heatmap of bin presence/absence for each genome.
        """

        # Perform hierarchical clustering on the rows and columns
        wide = self.bin_presence_wide
        wide_sorted = wide.iloc[linkage_order(wide.values, method="ward"), linkage_order(wide.values.T, method="ward")]

        # Set the edges of the bins so that the widths match the number of genes
        x = [0] + self.bin_size.reindex(wide_sorted.columns.values).cumsum().tolist()

        fig = go.Figure(
            data=[
                go.Heatmap(
                    z=wide_sorted.values,
                    x=x,
                    colorscale="blues",
                    showscale=False
                )
            ],
            layout=go.Layout(
                xaxis_title="Gene",
                yaxis_title="Genome",
                margin=dict(r=20),
                template=SIMPLE_TEMPLATE,
                width=width,
                height=height
            )
        )
        save_image(fig, file_prefix)

        return fig

    def calc_membership_vs_distance(
        self,
        min_n_genomes: int = 10,
        max_n_genomes: int = 100,
        n_genes: int = 100,
        max_distance: int = 1000000,
        random_state: int = 42
    ) -> pd.DataFrame:
        """
        For a random subset of genes, compute how similar they are in terms
        of their membership across all genomes, and then also compute their
        typical physical distance across those genomes (when they are both present).
        Then plot the relationship between these two metrics.

        To prevent a skewing by bin size, we'll randomly select a subset of bins
        and then randomly select a subset of genes from each bin.

        Parameters
        ----------
        min_n_genomes: int
            Minimum number of genomes that a gene must be present in to be considered.
        max_n_genomes: int
            Maximum number of genomes that a gene can be present in to be considered.
        n_genes: int
            Number of genes to select from each bin (up to the size of the bin).
        max_distance: int
            Maximum distance to consider for the genomic coordinates (in bp).
        random_state: int
            Seed for the gene subsampling.

        Returns
        -------
        DataFrame containing the membership and distance metrics.
        """

        n_genomes_per_gene = (
            self.align_genomes
            .reindex(columns=["sseqid", "genome"])
            .drop_duplicates()
            ["sseqid"]
            .value_counts()
        )
        genes_passing_filter = n_genomes_per_gene.loc[lambda x: (x >= min_n_genomes) & (x <= max_n_genomes)].index.tolist()

        # Pick a random subset of the genes
        genes = np.random.default_rng(random_state).choice(
            genes_passing_filter, size=n_genes, replace=False
        )

        df = (
            self.align_genomes
            .loc[self.align_genomes["sseqid"].isin(genes)]
            .assign(
                gene_position=lambda d: d["qstart"] + d["qend"] / 2
            )
        )

        # Compare each pair of genes to compute the membership and distance
        output = []
        for gene1, df1 in df.groupby("sseqid"):
            for gene2, df2 in df.groupby("sseqid"):
                if gene1 <= gene2:
                    continue
                output.append(dict(
                    gene1=gene1,
                    gene2=gene2,
                    membership=len(set(df1["genome"]) & set(df2["genome"])) / len(set(df1["genome"]) | set(df2["genome"])),
                    distance=self._compute_gene_distance(df1, df2, max_distance)
                ))

        return pd.DataFrame(output)

    def _compute_gene_distance(self, df1: pd.DataFrame, df2: pd.DataFrame, max_distance: int) -> float:
        """
        Compute the distance between two genes.
        """
        df = pd.concat([
            df1.assign(gene=lambda d: "gene1"),
            df2.assign(gene=lambda d: "gene2")
        ]).pivot(
            index=["genome", "qseqid"],
            columns="gene",
            values="gene_position"
        ).dropna()

        if df.shape[0] == 0:
            return max_distance
        else:
            return min(max_distance, np.abs(df["gene1"] - df["gene2"]).mean())

    def compare_membership_vs_distance(
        self,
        n_genes: int = 100,
        min_n_genomes: int = 10,
        max_n_genomes: int = 100,
        width: int = 500,
        height: int = 400,
        random_state: int = 42,
        file_prefix: str | None = None,
        **kwargs: dict[str, Any]
    ) -> go.Figure:
        """
        For a random subset of genes, compute how similar they are in terms
        of their membership across all genomes, and then also compute their
        typical physical distance across those genomes (when they are both present).
        Then plot the relationship between these two metrics.
        """

        df = (
            self.calc_membership_vs_distance(
                min_n_genomes, max_n_genomes, n_genes, random_state=random_state
            )
            .assign(
                distance_log10=lambda d: np.log10(d["distance"]),
                membership_bins=lambda d: d["membership"].apply(lambda x: round(x, 1))
            )
        )

        fig = px.box(
            data_frame=df,
            x="membership_bins",
            y="distance_log10",
            template=TEMPLATE,
            labels=dict(
                distance_log10="Mean distance between genes (bp)",
                membership_bins="Genome membership (Jaccard similarity)"
            ),
            width=width,
            height=height,
            **kwargs
        )
        fig.update_traces(marker=dict(size=4, opacity=0.6), line_width=1)
        fig.update_yaxes(
            tickmode='array',
            tickvals=[0, 1, 2, 3, 4, 5, 6],
            ticktext=["1", "10", "100", "1k", "10k", "100k", "1M"]
        )

        save_image(fig, file_prefix)
        return fig

    def bin_size_df(
        self,
        bins: int = 30,
    ) -> pd.DataFrame:
        """
        Histogram of bin sizes.
        """
        # Get the bin sizes
        vals = self.bin_size.copy().apply(np.log10)

        counts, bins = np.histogram(
            vals,
            bins=bins,
            weights=self.bin_size.copy()
        )

        bin_names = [
            (
                f"{10**bins[i-1]:.0f} - {10**bins[i]:.0f}"
            )
            for i in range(1, len(bins))
        ]
        bins = 0.5 * (bins[:-1] + bins[1:])

        return pd.DataFrame(dict(
            bin_size=bins,
            count=counts,
            bin_names=bin_names
        ))

    def bin_size_histogram(
        self,
        bins: int = 30,
        width: int = 500,
        height: int = 400,
        file_prefix: str | None = None
    ) -> go.Figure:

        df = self.bin_size_df(bins)

        fig = px.bar(
            data_frame=df,
            x="bin_size",
            y="count",
            labels=dict(
                bin_size="Pangenome bin size (genes)",
                count="Total gene content (genes)"
            ),
            template=TEMPLATE,
            hover_name="bin_names",
            width=width,
            height=height
        )
        fig.update_xaxes(
            tickmode='array',
            tickvals=[0, 1, 2, 3, 4, 5],
            ticktext=["1", "10", "100", "1k", "10k", "100k"]
        )
        save_image(fig, file_prefix)

        return fig

    def rarefaction_curve_data(self, n_reps: int = 10, random_state: int = 42) -> pd.DataFrame:
        data = []
        for rep in range(n_reps):
            # Take the bin presence matrix
            bin_presence = self.bin_presence_wide.copy()
            # Shuffle the rows, in an order that is reproducible across runs
            bin_presence = bin_presence.sample(
                frac=1, random_state=random_state + rep
            ).reset_index(drop=True)
            # Compute the cumulative sum by column (bin)
            cs = bin_presence.cumsum()
            # For each row, count the number of genes recovered
            n_genes = (cs > 0) * self.bin_size
            data.append(pd.DataFrame(dict(
                n_genomes=list(range(1, bin_presence.shape[0] + 1)),
                n_genes=n_genes.sum(axis=1)
            )))
        return (
            pd.concat(data)
            .groupby("n_genomes")
            ["n_genes"]
            .describe()
            .reset_index()
        )

    def rarefaction_curve(
        self,
        n_reps: int = 10,
        width: int = 500,
        height: int = 400,
        random_state: int = 42,
        file_prefix: str | None = None
    ) -> go.Figure:
        """
        Rarefaction curve of the pangenome.

        Parameters
        ----------
        n_reps: int
            Number of rarefaction replicates to simulate.
        random_state: int
            Seed for the order genomes are accumulated in.

        Returns
        -------
        Plotly figure of the rarefaction curve.
        """
        # Simulate the number of genes recovered with different numbers of subsampled genomes
        rf = self.rarefaction_curve_data(n_reps, random_state=random_state)

        fig = go.Figure(
            data=[
                go.Scatter(
                    x=rf["n_genomes"],
                    y=rf["50%"],
                    mode="lines",
                    line=dict(color=PRIMARY, width=2),
                    showlegend=False
                ),
                go.Scatter(
                    x=rf['n_genomes'],
                    y=rf['75%'],
                    mode='lines',
                    marker=dict(color=PRIMARY),
                    line=dict(width=0),
                    showlegend=False
                ),
                go.Scatter(
                    x=rf['n_genomes'],
                    y=rf['25%'],
                    marker=dict(color=PRIMARY),
                    line=dict(width=0),
                    mode='lines',
                    fillcolor='rgba(44, 111, 187, 0.25)',
                    fill='tonexty',
                    showlegend=False
                )
            ],
            layout=go.Layout(
                xaxis_title="Number of genomes",
                yaxis_title="Number of genes",
                yaxis_range=[0, None],
                template=TEMPLATE,
                width=width,
                height=height
            )
        )

        # Make the x axis log scale, ticked at the decades only
        fig.update_xaxes(
            type="log",
            dtick=1
        )

        save_image(fig, file_prefix)

        return fig

    def bin_gene_map(
        self,
        bin: str,
        width: int = 5,
        height: int = 5,
        remove_gene_id = True,
        remove_org_tag = True,
        text_offset = 0.025,
        font_size: float = 10.0,
        file_prefix: str | None = None
    ) -> go.Figure:
        """
        Map of genes in a bin.

        ``width`` and ``height`` are in inches, and set the span of the arrows;
        the labels standing over them extend the drawing above that. A panel
        meant for print is drawn at its printed width with ``font_size`` at
        the printed point size.
        """

        # Get a DataFrame with the gene coordinates
        # inferred from all of the genome alignments
        coords, group_offset = self._get_gene_coords(bin)

        # Customize the names
        coords = coords.assign(
            gene_label=coords['gene'].apply(self.gene_bins.set_index("gene_id")["gene_label"].get),
            label=lambda d: d['gene_label'].apply(
                lambda gene: self.customize_label(gene, remove_gene_id, remove_org_tag)
            )
        )

        max_x = np.max([coords['start'].max(), coords['stop'].max()])
        min_x = np.min([coords['start'].min(), coords['stop'].min()])
        span_x = max_x - min_x

        coords = coords.assign(
            start_x=lambda d: (d['start'] - min_x) / span_x,
            stop_x=lambda d: (d['stop'] - min_x) / span_x
        )

        fig, ax = plt.subplots(figsize=(width, height))
        draw_gene_labels(
            ax, coords[["start_x", "stop_x", "label"]].rename(columns={"start_x": "start", "stop_x": "stop"}),
            x0=0.0, x1=1.0, y=0.0, text_offset=text_offset, font_size=font_size,
            arrow_height=text_offset / 2,
        )
        ax.set_xlim(0, 1)
        # Room for the size bar below the genes and the start of the labels above
        ax.set_ylim(-1.6 * text_offset, 1.2 * text_offset)

        # The vertial lines work with an increment scaled to the text offset
        vertical_increment = text_offset / 10.

        # Draw a line to indicate each of the group offsets
        # It should be styled as a small vertical red line
        for offset_x in (group_offset / span_x).values:
            if offset_x > 0:
                ax.annotate(
                    '',
                    xytext=(offset_x, 0),
                    xy=(offset_x, -4 * vertical_increment),
                    arrowprops=dict(arrowstyle="-", color="red")
                )

        # Draw a line underneath the entire gene map
        ax.annotate(
            '',
            xytext=(0, -2 * vertical_increment),
            xy=(1, -2 * vertical_increment),
            arrowprops=dict(arrowstyle="|-|")
        )

        # Write the size underneath
        if span_x > 1000000:
            size_label = f"{span_x / 1000000:.1f} Mb"
        elif span_x > 1000:
            size_label = f"{span_x / 1000:.1f} Kb"
        else:
            size_label = f"{span_x:.0f} bp"
        ax.text(
            0.5,
            - (text_offset),
            size_label,
            fontsize=font_size,
            horizontalalignment='center',
            verticalalignment='bottom'
        )

        ax.axis("off")

        save_image(fig, file_prefix)

        # Optionally save the relative gene coordinates as CSV
        if file_prefix is not None:
            coords.to_csv(file_prefix + ".csv", index=False)

        return fig

    def bin_context_map(
        self,
        bin: str,
        n_genomes: int = 10,
        flank: int = 8000,
        max_gap: int = 20000,
        min_bin_fraction: float = 0.5,
        width: float = 9.0,
        font_size: float = 8.0,
        remove_gene_id: bool = True,
        remove_org_tag: bool = True,
        title: str | None = None,
        genome_names: Dict[str, str] | None = None,
        file_prefix: str | None = None,
    ) -> plt.Figure:
        """
        The bin's genes with their neighborhood in the genomes that carry
        them: the gene map above one row per genome, each row the stretch of
        contig around the bin with every gene on it drawn as an arrow.

        Contigs carrying at least ``min_bin_fraction`` of the bin's genes are
        placed in one coordinate space, and the ``n_genomes`` whose contigs
        span most of the window -- the bin plus ``flank`` bp either side --
        are shown, one contig per genome, with the GenBank copy of an
        assembly also present as RefSeq dropped. Rows are ordered by
        clustering on the genes they carry. With a ``file_prefix`` the genes
        of every row are also written as CSV.

        A bin's genes need not sit together: the window covers the largest
        run of them with no gap over ``max_gap`` bp, and the title says how
        many lie elsewhere. ``genome_names`` labels the rows (keyed by the
        genome's file name, as in ``helpers.ncbi.genome_names``); a genome
        it does not name is labeled by its accession.
        """
        aln = self.align_genomes
        in_bin = aln.loc[aln["bin"] == bin].drop_duplicates(["sseqid", "qseqid", "genome"])
        n_bin_genes = int(self.bin_size[bin])
        per_contig = in_bin.groupby(["genome", "qseqid"])["sseqid"].nunique()
        carrying = per_contig.loc[per_contig >= max(2, min_bin_fraction * n_bin_genes)]
        if carrying.empty:
            raise ValueError(f"No contig carries {min_bin_fraction:.0%} of {bin}")
        duplicates = genbank_duplicates(carrying.index.get_level_values("genome"))
        carrying = carrying.loc[~carrying.index.get_level_values("genome").isin(duplicates)]

        placed = Coords(in_bin.set_index(["genome", "qseqid"]).loc[carrying.index].reset_index())
        bin_coords = placed.to_df()
        clustered = _largest_cluster(bin_coords, max_gap)
        n_elsewhere = len(bin_coords) - len(clustered)
        bin_coords = clustered
        bin_lo = float(min(bin_coords["start"].min(), bin_coords["stop"].min()))
        bin_hi = float(max(bin_coords["start"].max(), bin_coords["stop"].max()))
        window = (bin_lo - flank, bin_hi + flank)

        labels = self.gene_bins.set_index("gene_id")["gene_label"]
        bin_genes = bin_coords.assign(
            label=bin_coords["gene"].map(labels).map(
                lambda name: self.customize_label(name, remove_gene_id, remove_org_tag)
            )
        )

        # Place each carrying contig from its bin genes alone, which is enough
        # to know how much of the window it spans; the genomes whose contigs
        # span most of it are kept, one contig each
        candidates = []
        for (genome, contig), n_carried in carrying.items():
            anchors = in_bin.loc[(in_bin["genome"] == genome) & (in_bin["qseqid"] == contig)].set_index("sseqid")
            transform = placed.fit(anchors["qstart"].to_dict(), anchors["qend"].to_dict())
            ends = sorted(transform(x) for x in (1, int(anchors["qlen"].iloc[0])))
            extent = (max(ends[0], window[0]), min(ends[1], window[1]))
            if extent[1] <= extent[0]:
                continue
            candidates.append({
                "genome": genome, "contig": contig, "n_carried": int(n_carried),
                "coverage": (extent[1] - extent[0]) / (window[1] - window[0]),
                "extent": extent, "transform": transform,
            })
        candidates.sort(key=lambda row: (-row["coverage"], -row["n_carried"], row["genome"]))
        chosen, seen = [], set()
        for row in candidates:
            if row["genome"] not in seen:
                chosen.append(row); seen.add(row["genome"])
            if len(chosen) == n_genomes:
                break

        # Every gene on each chosen contig, mapped into the shared space
        on_contigs = aln.set_index(["genome", "qseqid"]).sort_index()
        for row in chosen:
            on_contig = on_contigs.loc[(row["genome"], row["contig"])].drop_duplicates("sseqid")
            transform = row.pop("transform")
            genes = pd.DataFrame({
                "gene": on_contig["sseqid"].values,
                "start": on_contig["qstart"].map(transform).values,
                "stop": on_contig["qend"].map(transform).values,
                "bin": on_contig["bin"].values,
            })
            genes = genes.loc[(genes[["start", "stop"]].max(axis=1) > window[0]) & (genes[["start", "stop"]].min(axis=1) < window[1])]
            row["genes"] = genes.assign(in_bin=genes["bin"] == bin).sort_values("start")

        presence = pd.DataFrame(
            {row["genome"]: {gene: 1 for gene in row["genes"]["gene"]} for row in chosen}
        ).T.fillna(0).sort_index()
        by_genome = {row["genome"]: row for row in chosen}
        ordered = [by_genome[genome] for genome in order_rows(presence)]
        for row in ordered:
            row["genome_label"] = (genome_names or {}).get(row["genome"]) or _short_genome_name(row["genome"])

        title = title or f"{bin} and its neighborhood"
        if n_elsewhere:
            title += f" ({n_elsewhere} of its {n_bin_genes} genes lie outside this window)"
        fig = plot_gene_context(
            bin_genes,
            [dict(row, genome=row["genome_label"]) for row in ordered],
            window,
            title=title,
            width=width,
            font_size=font_size,
        )
        save_image(fig, file_prefix)
        if file_prefix is not None:
            pd.concat([
                row["genes"].assign(genome=row["genome"], contig=row["contig"], name=lambda d: d["gene"].map(labels))
                for row in ordered
            ]).to_csv(file_prefix + ".csv", index=False)
        return fig

    def _get_gene_coords(self, bin: str) -> pd.DataFrame:
        """
        Get the coordinates for every gene across every genome
        Filter to just the genes in this bin
        """
        aln = self.align_genomes.query(f"bin == '{bin}'")
        output = []
        while len(aln) > 0:
            output.append(Coords(aln).to_df())
            if len(output[-1]) == 0:
                break
            aln = aln.loc[~aln['sseqid'].isin(output[-1]['gene'])]

        df = pd.concat([df.assign(group=i) for i, df in enumerate(output)])

        # Assign a set of global coordinates to each gene
        # This will take into account the size of each group, which is the
        # maximum start or stop value within each group.
        group_sizes = (
            df.assign(end=df[['start', 'stop']].max(axis=1))
            .groupby("group")
            ['end'].max()
        )
        # To use those to build the global coordinates, take the cumulative sum
        group_offset = group_sizes.cumsum() - group_sizes
        
        df = df.assign(
            start=df["start"] + df["group"].apply(group_offset.get),
            stop=df["stop"] + df["group"].apply(group_offset.get)
        ).reset_index(drop=True)

        return df, group_offset

    @staticmethod
    def customize_label(label: str, remove_gene_id: bool, remove_org_tag: bool):
        if remove_gene_id:
            if label.startswith("Bin "):
                label = " - ".join(label.split(" - ", 2)[[0, 2]])
            else:
                label = label.split(" - ", 1)[1]
        if remove_org_tag:
            if " [" in label:
                label = label.rsplit(" [", 1)[0]
            if "MULTISPECIES: " in label:
                label = label.replace("MULTISPECIES: ", "")

        return label

    def bin_presence_heatmap(
        self,
        bins: str | List[str],
        width: int = 500,
        height: int = 400,
        title: str = "Bin presence by genome",
        tree_proportion: float = 0.5,
        horizontal_spacing: float = 0.,
        file_prefix: str | None = None
    ) -> go.Figure:
        """
        Which genomes carry each of ``bins``, as a strip of cells beside the
        genomes' ANI tree, with the genomes in the tree's leaf order.
        ``tree_proportion`` is the share of the width given to the tree.
        """
        if isinstance(bins, str):
            bins = [bins]

        tree = self.ani_tree
        df = (
            self.genome_content
            .loc[self.genome_content["bin"].isin(bins)]
            .assign(present=1)
            .pivot_table(index="genome", columns="bin", values="present")
            .reindex(index=tree.leaves_list, columns=bins)
            .fillna(0)
            .astype(int)
        )

        fig = make_subplots(
            rows=1,
            cols=2,
            shared_yaxes=True,
            horizontal_spacing=horizontal_spacing,
            column_widths=[tree_proportion, 1. - tree_proportion],
        )
        tree.plot_lines(fig, row=1, col=1)
        tree.plot_points(fig, mode="markers", row=1, col=1)
        fig.update_xaxes(title_text="ANI distance", row=1, col=1)
        fig.add_heatmap(
            z=df.values,
            x=df.columns.values,
            y=list(range(df.shape[0])),
            colorscale="blues",
            showscale=False,
            row=1,
            col=2,
        )
        fig.update_layout(
            height=height,
            width=width,
            template=SIMPLE_TEMPLATE,
            title=dict(text=title, x=0.5, xanchor="center"),
            margin=dict(r=20),
        )
        fig.update_yaxes(visible=False)
        save_image(fig, file_prefix)
        return fig

    @cached_property
    def ani_tree(self) -> Phylogeny:
        # Get the ANI distances
        ani_dist = self.ani_distances.copy()

        # Make a distance matrix in BioPython format
        dm = DistanceMatrix(
            names=list(ani_dist.index.values),
            matrix=[
                l[:(i+1)]
                for i, l in enumerate(ani_dist.values.tolist())
            ]
        )

        # Compute a hash of the ani_dist DataFrame which can be used to identify the tree
        tree_hash = hashlib.sha256(ani_dist.to_csv().encode()).hexdigest()

        # Cache the NJ tree as Newick, using the hash as the filename
        cache_file = Path(f".cache/pangenome_ani_tree/{tree_hash}.nwk")
        if cache_file.exists():
            logger.info(f"Loading ANI tree from cache: {cache_file}")
            tree = Phylo.read(cache_file, "newick")
        else:
            logger.info(f"Computing ANI tree and caching to: {cache_file}")
            constructor = DistanceTreeConstructor()
            tree = constructor.nj(dm)
            tree.root_at_midpoint()
            cache_file.parent.mkdir(exist_ok=True, parents=True)
            Phylo.write(tree, cache_file, "newick")

        distances = pd.DataFrame(dm.matrix, index=dm.names, columns=dm.names)

        return Phylogeny(
            name="ANI",
            tree=tree,
            distances=distances
        )