"""
Pangenome base class for gig-map-io.
"""

from functools import cached_property
import pandas as pd
import numpy as np
from plotly import graph_objects as go
import plotly.express as px

from ..helpers.sort_dataframe import sort_dataframe
from .dataset import Dataset


class Pangenome(Dataset):
    """
    Representation of a pangenome generated by gig-map.

    This is a minimal base class; concrete subclasses or helpers can add
    convenience methods for common gig-map outputs (e.g., gene presence/absence,
    annotations, etc.).

    DataFrame attributes are cached after first access to avoid reloading
    CSV files on subsequent accesses.
    """

    @cached_property
    def unbinned_genes_all_genomes_html(self) -> str:
        """
        Gene by genome heatmap HTML loaded from bin_pangenome/heatmap.unbinned_genes_all_genomes.html.
        """
        path = self.directory / "bin_pangenome/heatmap.unbinned_genes_all_genomes.html"
        return path.read_text()

    @cached_property
    def gene_bins(self) -> pd.DataFrame:
        """
        Gene bins DataFrame loaded from bin_pangenome/gene_bins.csv.

        Returns
        -------
        DataFrame containing gene bin assignments.
        """
        path = self.directory / "bin_pangenome" / "gene_bins.csv"
        return pd.read_csv(path)

    @cached_property
    def n_bins(self) -> int:
        """
        Number of unique (non-null) bins in gene_bins.
        """
        return int(self.gene_bins["bin"].dropna().nunique())

    @cached_property
    def n_genes(self) -> int:
        """
        Number of genes which are part of bins in the pangenome.
        """
        return int(self.gene_bins.dropna(subset=["bin"]).shape[0])

    @cached_property
    def genome_content(self) -> pd.DataFrame:
        """
        Genome content DataFrame loaded from bin_pangenome/genome_content.long.csv.

        Returns
        -------
        DataFrame containing genome content data.
        """
        path = self.directory / "bin_pangenome" / "genome_content.long.csv"
        return pd.read_csv(path, low_memory=False)

    @cached_property
    def bin_presence_wide(self) -> pd.DataFrame:
        """
        Wide dataframe of bin presence/absence for each genome. Each column is a bin, each row is a genome.
        """
        return (
            self.genome_content
            .assign(present=(self.genome_content["prop_genes_detected"] >= 0.5).astype(int))
            .reindex(columns=["genome", "bin", "present"])
            .dropna()
            .drop_duplicates()
            .pivot(
                index="genome",
                columns="bin",
                values="present"
            )
            .fillna(0)
        )

    @cached_property
    def bin_size(self) -> pd.DataFrame:
        """
        Number of genes in each bin.
        """
        return self.gene_bins["bin"].value_counts()

    def bin_genome_heatmap(self) -> go.Figure:
        """
        Heatmap of bin presence/absence for each genome.
        """

        # Perform hierarchical clustering on the rows and columns
        wide_sorted = sort_dataframe(
            sort_dataframe(
                self.bin_presence_wide.copy().T,
                method="ward"
            ).T,
            method="ward"
        )

        # Set the edges of the bins so that the widths match the number of genes
        x = [0] + self.bin_size.reindex(wide_sorted.columns.values).cumsum().tolist()

        return go.Figure(
            data=[
                go.Heatmap(
                    z=wide_sorted.values,
                    x=x,
                    colorscale="blues",
                    showscale=False
                )
            ],
            layout=go.Layout(
                xaxis_title="Gene",
                yaxis_title="Genome",
                template="simple_white"
            )
        )

    def bin_size_histogram(self, bins: int = 30) -> go.Figure:
        """
        Histogram of bin sizes.
        """
        # Get the bin sizes
        vals = self.bin_size.copy().apply(np.log10)

        counts, bins = np.histogram(
            vals,
            bins=bins,
            weights=self.bin_size.copy()
        )

        bin_names = [
            (
                f"{10**bins[i-1]:.0f} - {10**bins[i]:.0f}"
            )
            for i in range(1, len(bins))
        ]
        bins = 0.5 * (bins[:-1] + bins[1:])

        return px.bar(
            x=bins,
            y=counts,
            labels={'x':"Pangenome Bin Size (# of Genes)", 'y':'Total Gene Content'},
            template="simple_white",
            hover_name=bin_names
        )

    def rarefaction_curve(self, max_genomes: int = 100) -> go.Figure:
        """
        Rarefaction curve of the pangenome.

        Parameters
        ----------
        max_genomes: int
            Maximum number of genomes to simulate.

        Returns
        -------
        Plotly figure of the rarefaction curve.
        """
        # Simulate the number of genes recovered with different numbers of subsampled genomes
        df = self.bin_presence_wide * self.bin_size
        rf = pd.DataFrame([
            dict(
                n_genomes=n_genomes,
                **pd.Series([
                    df.sample(n_genomes).max().sum()
                    for rep in range(100)
                ]).describe()
            )
            for n_genomes in range(1, min(max_genomes, df.shape[0]))
        ])

        fig = go.Figure(
            data=[
                go.Scatter(
                    x=rf["n_genomes"],
                    y=rf["50%"],
                    mode="lines",
                    line=dict(color='rgb(31, 119, 180)'),
                    showlegend=False
                ),
                go.Scatter(
                    x=rf['n_genomes'],
                    y=rf['75%'],
                    mode='lines',
                    marker=dict(color="#444"),
                    line=dict(width=0),
                    showlegend=False
                ),
                go.Scatter(
                    x=rf['n_genomes'],
                    y=rf['25%'],
                    marker=dict(color="#444"),
                    line=dict(width=0),
                    mode='lines',
                    fillcolor='rgba(68, 68, 68, 0.3)',
                    fill='tonexty',
                    showlegend=False
                )
            ],
            layout=go.Layout(
                xaxis_title="Number of Genomes",
                yaxis_title="Number of Genes",
                template="simple_white"
            )
        )
        return fig
