"""
PangenomePhylogeny base class for gig-map-io.
"""

from .dataset import Dataset


class PangenomePhylogeny(Dataset):
    """
    Representation of a pangenome phylogeny generated by gig-map.

    This class represents phylogenetic information associated with a pangenome.
    """
