"""
PangenomePhylogeny base class for gig-map-io.
"""

from .dataset import Dataset
from pathlib import Path
from Bio import Phylo
import pandas as pd
from ..helpers.phylogeny import Phylogeny


class PangenomePhylogeny(Dataset):
    """
    Representation of a pangenome phylogeny generated by gig-map.

    This class represents phylogenetic information reconstructed by multi-genome
    alignment of the nucleotide sequences of the genes in a pangenome.
    The phylogeny is merged for each pangenome bin, and the resulting phylogeny
    is used to reconstruct the phylogenetic relationship between the genes in
    the pangenome.
    """
    def __init__(self, directory: str | Path) -> None:
        super().__init__(directory)

    def _newick_file(self, bin_id: str) -> Path:
        return self.directory / "raxml" / f"{bin_id}.msa.raxml.bestTree"

    def newick(self, bin_id: str, root_at_midpoint: bool = True) -> str:
        """
        Make the tree, root at midpoint, and then return the Newick string.
        """
        tree = Phylo.read(self._newick_file(bin_id), "newick")
        if root_at_midpoint:
            tree.root_at_midpoint()
        return tree.format("newick")

    def tree(self, bin_id: str) -> Phylogeny:
        # Get the phylogey from the newick file
        tree = Phylo.read(self._newick_file(bin_id), "newick")

        # Root at midpoint
        tree.root_at_midpoint()

        # Compute the distances between the leaves
        distances = pd.DataFrame(
            {
                leaf1.name: {
                    leaf2.name: tree.distance(leaf1, leaf2)
                    for leaf2 in tree.get_terminals()
                }
                for leaf1 in tree.get_terminals()
            }
        )

        return Phylogeny(
            name=bin_id,
            tree=tree,
            distances=distances
        )