"""
Phylogeny base class for gig-map-io.
"""

from .dataset import Dataset
from pathlib import Path


class Phylogeny(Dataset):
    """
    Representation of a pangenome phylogeny generated by gig-map.

    This class represents phylogenetic information reconstructed by multi-genome
    alignment of the nucleotide sequences of the genes in a pangenome.
    The phylogeny is merged for each pangenome bin, and the resulting phylogeny
    is used to reconstruct the phylogenetic relationship between the genes in
    the pangenome.
    """
    def __init__(self, directory: str | Path) -> None:
        super().__init__(directory)

