"""
PangenomePhylogeny base class for gig-map-io.
"""

from .dataset import Dataset
from pathlib import Path
from Bio import Phylo
from ..helpers.phylogeny import Phylogeny


class PangenomePhylogeny(Dataset):
    """
    Representation of a pangenome phylogeny generated by gig-map.

    This class represents phylogenetic information reconstructed by multi-genome
    alignment of the nucleotide sequences of the genes in a pangenome.
    The phylogeny is merged for each pangenome bin, and the resulting phylogeny
    is used to reconstruct the phylogenetic relationship between the genes in
    the pangenome.
    """
    def _newick_file(self, bin_id: str) -> Path:
        return self.directory / "raxml" / f"{bin_id}.msa.raxml.bestTree"

    def tree(self, bin_id: str) -> Phylogeny:
        """The bin's gene tree, rooted at its midpoint."""
        tree = Phylo.read(self._newick_file(bin_id), "newick")
        tree.root_at_midpoint()
        return Phylogeny(name=bin_id, tree=tree)