[@@]
"""
Core data model classes for gig-map-io.

These classes define the public interfaces for working with outputs of the
gig-map workflow, without tying the implementation to any specific storage
backend.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Mapping, Optional, Protocol

import pandas as pd


class SupportsReadTable(Protocol):
    """Protocol for backends that can read tabular data."""

    def read_table(self, resource: str | Path, *, fmt: str = "csv", **kwargs: Any) -> pd.DataFrame:
        ...


@dataclass
class Pangenome:
    """
    Representation of a pangenome generated by gig-map.

    This is a minimal base class; concrete subclasses or helpers can add
    convenience methods for common gig-map outputs (e.g., gene presence/absence,
    annotations, etc.).
    """

    backend: SupportsReadTable
    root: Path

    def gene_presence_absence(self, resource: str | Path = "gene_presence_absence.csv", **kwargs: Any) -> pd.DataFrame:
        """
        Load the gene presence/absence table.

        Parameters
        ----------
        resource:
            Relative path or backend-specific identifier for the table.
        kwargs:
            Passed through to the backend's `read_table` implementation.
        """
        return self.backend.read_table(self.root / resource, **kwargs)


@dataclass
class ContrastMetagenomes:
    """
    Representation of a contrast between metagenomes (e.g., case vs control).
    """

    backend: SupportsReadTable
    root: Path

    def summary(self, resource: str | Path = "contrast_summary.csv", **kwargs: Any) -> pd.DataFrame:
        """Load a high-level summary table for the contrast."""
        return self.backend.read_table(self.root / resource, **kwargs)


@dataclass
class PangenomeBin:
    """
    Representation of a single pangenome bin (e.g., a MAG or species bin).
    """

    backend: SupportsReadTable
    root: Path
    bin_id: str

    def abundance(self, resource: Optional[str | Path] = None, **kwargs: Any) -> pd.DataFrame:
        """
        Load abundance information for this bin.

        Parameters
        ----------
        resource:
            Optional override for the resource name; by default, will look up
            `<bin_id>_abundance.csv` under `root`.
        """
        if resource is None:
            resource = f"{self.bin_id}_abundance.csv"
        return self.backend.read_table(self.root / resource, **kwargs)

