"""
Pangenome base class for gig-map-io.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pandas as pd


@dataclass
class Pangenome:
    """
    Representation of a pangenome generated by gig-map.

    This is a minimal base class; concrete subclasses or helpers can add
    convenience methods for common gig-map outputs (e.g., gene presence/absence,
    annotations, etc.).
    """

    directory: Path

    def gene_presence_absence(self, filename: str | Path = "gene_presence_absence.csv", **kwargs: Any) -> pd.DataFrame:
        """
        Load the gene presence/absence table.

        Parameters
        ----------
        filename:
            Name of the CSV file relative to the directory.
        kwargs:
            Passed through to pandas `read_csv`.
        """
        path = self.directory / filename
        return pd.read_csv(path, **kwargs)


